Dev me18 examples
Analog-Devices-MSDK/msdk pull request #169
Opened 2022-10-17 12:57 UTC by ozersa

MAX32690 examples reviewed
examples table [here](https://confluence.maxim-ic.com/display/MSW/MSDK+Example+Validation+and+Adding+Missing+Boards)
The issue list [here](https://jira.maxim-ic.com/browse/MSDK-659?src=confmacro)

2022-10-19 13:43 UTC, sihyung-maxim submitted a review, later dismissed

2022-10-19 16:47 UTC, sihyung-maxim requested changes
There are still some leftover build errors. These two were the only ones I found.

2022-10-19 16:47 UTC, sihyung-maxim commented on Examples/MAX32690/HBMC/main.c
> +    mem.latency_cycle = MXC_HPB_LATENCY_6;
Please update to MXC_HPB_LAT_6.

2022-10-19 16:47 UTC, sihyung-maxim commented on Examples/MAX32690/HBMC/main.c
> +    mem.latency_cycle = MXC_HPB_LATENCY_5;
Please update to MXC_HPB_LAT_5.

2022-10-19 17:02 UTC, ozersa commented on Examples/MAX32690/HBMC/main.c
> +    mem.latency_cycle = MXC_HPB_LATENCY_5;
Updated

2022-10-20 02:12 UTC, sihyung-maxim approved these changes

2022-10-20 21:27 UTC, Jake-Carter reviewed
Looks good.  One minor issue to resolve to get the HBMC project compatible with the SBT rules.

2022-10-21 07:25 UTC, ozersa commented on Examples/MAX32690/HBMC/project.mk
> +LINKERFILE=$(TARGET_LC)_hpb.ld
Good catch!
Fix [here](https://github.com/Analog-Devices-MSDK/msdk/pull/169/commits/e6fb0103f356f1f6ae4477fb833b09b9fb8bdd7b)

Related but different topic:
This case demonstrate that: For current structure user can not overwrite linker file for SBT=1 mode.
Depend on your above build, the linker file set to max32690_hpb.ld , but due to SBT=1 the linker file force to use max32690_sla.ld.
Might need to be considered in future.

2022-10-21 16:48 UTC, sihyung-maxim approved these changes

2022-10-21 17:28 UTC, Jake-Carter commented on Examples/MAX32690/HBMC/project.mk
> +LINKERFILE=$(TARGET_LC)_hpb.ld
True, we might want to move the default linkerfile selection to gcc.mk in the future.  Then SBT-config.mk can use `?=` to override the linkerfile only if none is specified by project.mk

2022-10-21 17:29 UTC, Jake-Carter approved these changes
Looks good!

2022-10-24 07:23 UTC, ozersa commented
@sihyung-maxim , @Jake-Carter Could you rebase and merge it, I do not have permission to do it.
Thanks

2022-10-24 20:24 UTC, lorne-maxim commented
Sadik, I have restricted the merges into main as squash and merge only.  I realize some history will be lost, but I want to keep the main branch's history as clean as possible.  Its commit history will be used to generate the release notes for each release.  If the main branch becomes cluttered with too many intermediate commits (e.g., all the "clang-format bot reformatting" messages) from each PR, creating the release notes is going to be challenging.  Because we are restricted to squash and merge only, I'd rather have a different PR for each feature or bug fix.  Alternatively, editing the commit notes of the squashed commit to include only the major points of that PR will also work.

2022-10-25 07:35 UTC, ozersa commented
@lorne-maxim  that's OK. 
Could anyone merge it to the main branch?
I do not have permission to do it.
Thanks.

2022-10-25 12:43 UTC, merged

2022-10-25 12:43 UTC, lorne-maxim commented
@ozersa, This PR has been merged.  You can delete the branch if you are finished with it.