implements transfer progress bar
Analog-Devices-MSDK/msdk pull request #175
Opened 2022-10-17 20:38 UTC by EdwinFairchild

I implemented this because the current output overflows when using 2M.
see it in action  here https://media.giphy.com/media/VP4Ua0yKmRa0YYv5UH/giphy.gif

Could be that less is more sometimes, I can make it just simply print percent line after line. 
Your call.

2022-10-20 03:07 UTC, lorne-maxim requested changes

2022-10-20 03:07 UTC, lorne-maxim commented on Examples/MAX32655/BLE_otac/datc_main.c
> +                    WdxcFtcSendPutReq(connId, datcCb.fileList[connId - 1][0].handle,
clang-format should catch this, but you'll need braces around the body of this 'if' block.

2022-10-20 03:07 UTC, lorne-maxim commented on Examples/MAX32655/BLE_otas/wdxs_file.c
> +        if (packetCount >= (fileHeader.fileLen / 224) + 1) {
Add comment on why 224 or use #define.

2022-10-21 16:56 UTC, sihyung-maxim reviewed
Did you merge the latest changes from main to this branch? Not sure why the linter is complaining, but maybe updating this branch will resolve the linter errors.

2022-10-21 17:00 UTC, EdwinFairchild commented
@sihyung-maxim yeah when #192 get merged ill merge main into this again and it should clear things up

2022-10-21 17:13 UTC, Jake-Carter commented
> @sihyung-maxim yeah when #192 get merged ill merge main into this again and it should clear things up

@EdwinFairchild merged

2022-10-21 18:07 UTC, EdwinFairchild commented
/clang-format-run

2022-10-26 19:25 UTC, closed without merging