ME11: ME12: Synced SVD files to Register files.
Analog-Devices-MSDK/msdk pull request #202
Opened 2022-10-24 20:38 UTC by sihyung-maxim

Changes:
- Peripheral SVD files and register files should now match for ME11 and ME12.
- Updated copyright notices.
- Updated max32660.svd and max32662.svd.
- register files for ME11 and ME12 should now pass linter.

2022-10-24 21:13 UTC, sihyung-maxim commented
/clang-format-run

2022-11-01 15:14 UTC, Jacob-Scheiffler requested changes

2022-11-01 15:14 UTC, Jacob-Scheiffler commented on Libraries/CMSIS/Device/Maxim/MAX32660/Include/spi_regs.h
> +#define MXC_F_SPI_CTRL2_SS_POL                         ((uint32_t)(0x1UL << MXC_F_SPI_CTRL2_SS_POL_POS)) /**< CTRL2_SS_POL Mask */
Add SS1/2/3_LOW and SS1/2/3_HIGH?

2022-11-01 15:14 UTC, Jacob-Scheiffler commented on Libraries/CMSIS/Device/Maxim/MAX32660/Include/spimss_regs.h
> +#define MXC_V_SPIMSS_INT_FL_TUND_NOEVENT               ((uint32_t)0x0UL) /**< INT_FL_TUND_NOEVENT Value */
INACTIVE and PENDING?

2022-11-01 15:14 UTC, Jacob-Scheiffler commented on Libraries/CMSIS/Device/Maxim/MAX32660/Include/spimss_regs.h
> +#define MXC_V_SPIMSS_I2S_CTRL_I2S_MUTE_REPLACED        ((uint32_t)0x1UL) /**< I2S_CTRL_I2S_MUTE_REPLACED Value */
I2s_MUTE_MUTE instead? Or Omit?

2022-11-02 15:31 UTC, sihyung-maxim commented on Libraries/CMSIS/Device/Maxim/MAX32660/Include/gpio_regs.h
> +#define MXC_R_GPIO_EN2_CLR                 ((uint32_t)0x0000007CUL) /**< Offset from GPIO Base Address: <tt> 0x007C</tt> */
The ME11 doesn't support the addition of the EN3 registers. The ME12 was the first part to introduce the new set of EN3 registers.

The ME11 UG uses IS and SR names.

2022-11-02 15:31 UTC, sihyung-maxim commented
I removed the enum values for fields that are 1 bit wide (as they should be).

2022-11-04 15:40 UTC, lorne-maxim approved these changes

2022-11-04 19:58 UTC, Jacob-Scheiffler approved these changes

2022-11-04 20:06 UTC, merged