ME17: AI85: ME20: Synced SVD files to Register Files.
Analog-Devices-MSDK/msdk pull request #206
Opened 2022-10-25 14:44 UTC by sihyung-maxim

AI85 and ME20 parts were built up from the ME17, so those two parts are dependent on some of the ME17-dependent SVD files.
Changes:
- Synced peripheral SVD files to the respective register file.
- Updated max32655.svd, max78000.svd, and max32680.svd.
- Updated copyright notices.
- Resolve SVDConv errors.
- Removed unsupported PWM mode from WUT peripheral.

2022-10-25 20:36 UTC, sihyung-maxim commented
I fixed the build errors in the AI85 CNN-related examples. The GCR_PCLKDIV.CNNCLKSEL[17:17] field had a manually coded-in enum definition called MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK which wasn't added by the register generation scripts since they don't add enum definitions for fields that are 1 bit wide (only two possible enum value options). This is to prevent register files from being too long and unwieldy, especially for files like gcr_regs.h where there are many registers and fields to define.

Any thoughts on keeping MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK defined? It's not a good long term solution to keep adding this definition by hand.

2022-11-03 17:26 UTC, Jacob-Scheiffler commented on Libraries/CMSIS/Device/Maxim/MAX32655/Include/wut_regs.h
> +#define MXC_S_WUT_CTRL_TMODE_COUNTER                   (MXC_V_WUT_CTRL_TMODE_COUNTER << MXC_F_WUT_CTRL_TMODE_POS) /**< CTRL_TMODE_COUNTER Setting */
Modes 2-7 are marked as reserved in the UG.

2022-11-03 18:04 UTC, Jacob-Scheiffler reviewed
My comments on the MAX32655 WUT regs also go for the MAX32680 and MAX78000 WUT regs.

2022-11-04 17:40 UTC, lorne-maxim approved these changes

2022-11-04 19:54 UTC, sihyung-maxim commented on Libraries/CMSIS/Device/Maxim/MAX32655/Include/wut_regs.h
> +#define MXC_F_WUT_PRESET_PRESET_POS                    0 /**< PRESET_PRESET Position */
They should be included, at least SNAPSHOT for the Trim functions.

2022-11-04 19:55 UTC, sihyung-maxim commented on Libraries/CMSIS/Device/Maxim/MAX32655/Include/wut_regs.h
> +#define MXC_V_WUT_CTRL_TMODE_COUNTER                   ((uint32_t)0x2UL) /**< CTRL_TMODE_COUNTER Value */
Removed.

2022-11-04 20:00 UTC, lorne-maxim approved these changes

2022-11-04 20:17 UTC, sihyung-maxim commented on Examples/MAX78000/CNN/UNet-demo/main.c
> +    cnn_enable((0 << MXC_F_GCR_PCLKDIV_CNNCLKSEL_POS), MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);
Talked to Jake about this. This might be something that was manually added. Still investigating.

2022-11-04 20:46 UTC, sihyung-maxim commented on Libraries/CMSIS/Device/Maxim/MAX78000/Include/bbfc_regs.h
> -// The BBFC block has been renamed to GCFR.
@Jake-Carter The BBFC is just a deprecated name to the GCFR, and this bbfc_regs.h file just points to gcfr_regs.h. It has been out for a year now, so there's been plenty of grace time to use the GCFR name. The CNN examples are the only files that use bbfc_regs.h. Do you think this should still be included?

2022-11-04 20:47 UTC, sihyung-maxim commented on Libraries/CMSIS/Device/Maxim/MAX32655/Include/wut_regs.h
> +#define MXC_V_WUT_CTRL_TMODE_COUNTER                   ((uint32_t)0x2UL) /**< CTRL_TMODE_COUNTER Value */
Actually, I left all the registers and modes in (except for PWM). The Bluetooth Libraries use the other modes.

2022-11-04 21:31 UTC, EdwinFairchild commented
This will keep failing because the branch was made before a certain fix was implemented in the workflow that caused a false failed test. You can ignore the failure, or merge main into this and it will pass.

2022-11-04 21:48 UTC, Jake-Carter commented on Libraries/CMSIS/Device/Maxim/MAX78000/Include/bbfc_regs.h
> -// The BBFC block has been renamed to GCFR.
@sihyung-maxim Yes, we should still keep this file around.  New projects can easily be updated to use the new definition, but we should not intentionally break backwards compatibility in any way and there's no maintenance overhead for this file.

If it actually had some conflicting register definitions in it it'd be a different story, but it's just a passthrough file.

2022-11-04 21:58 UTC, Jake-Carter commented on Examples/MAX78000/CNN/UNet-demo/main.c
> +    cnn_enable((0 << MXC_F_GCR_PCLKDIV_CNNCLKSEL_POS), MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);
Found it:  
* https://github.com/MaximIntegratedAI/ai8x-synthesis/blob/dd91220a323f69a6e2016fc6a0419ea58d802c92/izer/toplevel.py#L547

Another backwards compatibility issue...  The izer has been using this for a very long time and the old register value currently exists in `gcr_regs.h`:  https://github.com/Analog-Devices-MSDK/msdk/blob/f1301b69c15c8ef34508ebc7b1870190ea4ca5ac/Libraries/CMSIS/Device/Maxim/MAX78000/Include/gcr_regs.h#L391

We can update the izer and examples to use the new definition, but we should not break backwards compatibility by removing `MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK`

2022-11-07 15:19 UTC, Jacob-Scheiffler submitted a review, later dismissed

2022-11-07 16:03 UTC, Jake-Carter requested changes
Should resolve a few of the backwards compatibility issues before merging

2022-11-08 14:23 UTC, sihyung-maxim commented on Examples/MAX78000/CNN/UNet-demo/main.c
> +    cnn_enable((0 << MXC_F_GCR_PCLKDIV_CNNCLKSEL_POS), MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);
MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK will be something that has to be manually added if we want to keep this definition. Is there a CNN header file where we can add this definition so as to not have to worry about adding them by hand each time the register files are generated?

2022-11-08 14:42 UTC, sihyung-maxim commented on Libraries/CMSIS/Device/Maxim/MAX78000/Include/bbfc_regs.h
> + * @note    This file is @deprecated.
Adding this note as a unique token to exclude checking these registers files for the new Register_SVD workflow. Let me know if you think there's a better way to handle this.

2022-11-08 14:46 UTC, sihyung-maxim commented on Libraries/CMSIS/Device/Maxim/MAX78000/Include/bbfc_regs.h
> -// The BBFC block has been renamed to GCFR.
I added it back in with some updates.

2022-11-08 15:33 UTC, lorne-maxim approved these changes

2022-11-09 14:34 UTC, sihyung-maxim commented
/clang-format-run

2022-11-10 23:45 UTC, Jake-Carter commented
@sihyung-maxim looks good, I just want to run a quick regression test of the izer output against these changes.  Will do tomorrow and approve if there are no build issues

2022-11-14 18:58 UTC, Jake-Carter approved these changes
Approved - latest izer output for AI85 builds cleanly for all projects.

FYI only the includes below are used in the generated main.c files.  Looks like the other inclusions (`gcfr_regs.h`) are manual additions for a few demo-type projects
```C
 #include <stdlib.h>
 #include <stdint.h>
 #include <string.h>
 #include <stdio.h>
 #include "mxc.h"
 #include "cnn.h"
 #include "sampledata.h"
 #include "sampleoutput.h"
```

2022-11-14 19:00 UTC, merged