MSDK-932: Fixing MAX32650 AES_KEY register offsets.
Analog-Devices-MSDK/msdk pull request #209
Opened 2022-10-26 20:36 UTC by Jacob-Scheiffler

2022-10-26 20:45 UTC, sihyung-maxim requested changes
You'll also have to update the max32650.svd file to include the updated registers.

2022-10-26 20:45 UTC, sihyung-maxim commented on Libraries/CMSIS/Device/Maxim/MAX32650/Include/aes_key_regs.h
> +    __IO uint32_t aes_key3[4];          /**< <tt>\b 0x180:</tt> AES_KEY AES_KEY3 Register */
This is register file is outdated. Use the register SVD scripts to regenerate this file so you don't have to make all these changes.

2022-11-04 19:17 UTC, sihyung-maxim approved these changes

2022-11-04 19:35 UTC, EdwinFairchild commented
This branch was made before some fixes to the failing test in the workflow. You can either merge main into this. Or you can ignore the failed test honestly its a false result.

2022-11-04 20:02 UTC, lorne-maxim approved these changes

2022-11-04 20:25 UTC, merged