Dev me20 examples
Analog-Devices-MSDK/msdk pull request #219
Opened 2022-11-01 11:39 UTC by ozersa

MAX32680 examples reviewed.
Detail [here](https://confluence.maxim-ic.com/display/MSW/MSDK+Example+Validation+and+Adding+Missing+Boards)
Unresolved JIRA tickets
[MAX32680](https://jira.maxim-ic.com/browse/MSDK-658)

2022-11-01 17:49 UTC, Jake-Carter requested changes
Looks good.  Only thing to resolve is the return value mismatch

2022-11-01 17:50 UTC, Jake-Carter commented
/clang-format-run

2022-11-02 05:58 UTC, ozersa commented on Examples/MAX32680/AES/main.c
> +    return fail;
In fact "0" is meaning value, for fail cases any non-zero values should be fine.
Anyway reverted.

2022-11-02 06:00 UTC, ozersa commented on Examples/MAX32680/DMA/main.c
> +    return fail;
Thanks I was aware of it.
To simplify it reverted some changes.

2022-11-02 06:00 UTC, ozersa commented on Examples/MAX32680/LP/main.c
> +	PRINT("****Low Power Mode Example****\n\n");
Thanks, done.

2022-11-02 17:30 UTC, Jake-Carter approved these changes

2022-11-02 21:18 UTC, Jake-Carter commented on Examples/MAX32680/AES/main.c
> +    return fail;
Thanks.  I think it's just good to have consistency.  It may save us some headaches in the future

2022-11-04 17:01 UTC, sihyung-maxim commented
I've been holding on approving some of the PRs until the register updates are pushed in.

2022-11-04 20:57 UTC, lorne-maxim approved these changes

2022-11-04 21:31 UTC, sihyung-maxim approved these changes

2022-11-04 21:34 UTC, merged