Added new project BLE_fit_FreeRTOS for MAX32655 and fixed BLE_fit dual-core problems.
Analog-Devices-MSDK/msdk pull request #220
Opened 2022-11-02 15:30 UTC by yc-adi

Based on MAX32655/BLE_fit project, applied it into FreeRTOS.
Fixed the dual-core problems in MAX32655/BLE_fit.

2022-11-02 16:32 UTC, yc-adi commented
Added script .github/workflows/local_clang-format-check.sh to apply the clang format check on the local machine.

2022-11-04 21:15 UTC, lorne-maxim requested changes
Please add the new example to Libraries\Boards\MAX32655\*\examples.txt for each board on which the example is expected to be compatible with.

2022-11-08 15:35 UTC, lorne-maxim approved these changes

2022-11-08 15:37 UTC, lorne-maxim commented
@sihyung-maxim, will the spaces before the Dual_core_sync examples cause any problems with the new project wizard?

2022-11-14 14:27 UTC, sihyung-maxim submitted a review, later dismissed

2022-11-14 14:27 UTC, sihyung-maxim commented on Examples/MAX32655/BLE_fit_FreeRTOS/.cproject
> +<listOptionValue builtIn="false" value="&quot;${MAXIM_PATH}/Libraries/FreeRTOS/Source/portable/GCC/RISC-V&quot;"/>
Not a big deal functionally, but the formatting got messed up in .cproject file.

2022-11-14 14:40 UTC, sihyung-maxim requested changes

2022-11-14 14:40 UTC, sihyung-maxim commented on Libraries/Boards/MAX32655/EvKit_V1/examples.txt
> +    Dual_core_sync_riscv
In order for the project wizard to locate examples in subdirectories (like the AI85 CNN examples), you need to attach the path to the example name in one line. So these three lines should be replaced with:
`Dual_core_sync/Dual_core_sync_arm`
`Dual_core_sync/Dual_core_sync_riscv`

2022-11-14 19:53 UTC, sihyung-maxim approved these changes

2022-11-14 20:34 UTC, lorne-maxim approved these changes

2022-11-14 20:55 UTC, merged