Updated documentation of ARM/RISC-V demos
Analog-Devices-MSDK/msdk pull request #268
Opened 2022-11-30 02:15 UTC by vicloginov

2022-11-30 18:05 UTC, aniktash reviewed
Also suggest to remove README.pdf in kws project

2022-11-30 18:05 UTC, aniktash commented on Examples/MAX78000/CNN/kws20_demo-riscv/README.md
> +If you are using Windows, open MinGW window and start OpenOCD:
a MinGW

2022-12-01 21:58 UTC, Jake-Carter requested changes
Looks good!  Just a couple minor things below.  

I will add similar instructions to the command-line section in the WIP User Guide, so we could also consolidate the instructions to a single place and link to it from these readmes:  https://github.com/Analog-Devices-MSDK/msdk/pull/273

With the corrections below this works until we can flesh out the RISC-V content in the UG more.

2022-12-01 21:58 UTC, Jake-Carter commented on Examples/MAX78000/CNN/faceid_evkit-riscv/README.md
> +openocd -s $MAXIM_PATH/Tools/OpenOCD/scripts -f interface/ftdi/olimex-arm-usb-ocd-h.cfg -f target/max78000_riscv.cfg
RISC-V OpenOCD should be launched on a separate port

Ex: `openocd -c "gdb_port 3334" ...`

2022-12-01 21:58 UTC, Jake-Carter commented on Examples/MAX78000/CNN/faceid_evkit-riscv/README.md
> +./openocd -f tcl/interface/ftdi/olimex-arm-usb-ocd-h.cfg -f tcl/target/max78000_riscv.cfg
`./openocd` may not work.  Linux should be able to use the same command instead of the tcl-based lookups

2022-12-02 00:45 UTC, Jake-Carter approved these changes

2022-12-08 20:27 UTC, yc-adi approved these changes

2022-12-08 20:46 UTC, merged