Adding Coremark example.
Analog-Devices-MSDK/msdk pull request #336
Opened 2023-01-17 21:02 UTC by Jacob-Scheiffler

The coremark example was originally written for the MAX32655. This PR adds the original example along with the ported to each of the other micros except for the MAX32690. The MAX32690 will possibly added later, still determining whether this example is causing the bricked MAX32690's.

2023-02-20 22:19 UTC, sihyung-maxim commented
The icc_regs.h was removed from the ME55. Just found a new bug in the SVD checker though. An unsupported register file was removed, and the SVD action doesn't check for register file removals and sees the "removal" as a register file change. Because the register file isn't supported according to the list of supported peripherals per part in the SVD scripts and the SVD action sees this as a register file change, the SVD action will attempt to generate icc_regs.h but fails when it can't find the unsupported register file's corresponding peripheral SVD file. 

I will have to update this once this PR is merged because the Verify_Register_SVD workflow has had some updates.

2023-02-20 22:26 UTC, sihyung-maxim approved these changes
Interesting how the main program is located in Libraries/Coremark/core_main.c, but the examples only contain core_portme.c/.h.

2023-02-23 00:27 UTC, Jake-Carter requested changes
Yeah please add some comments to project.mk and some documentation in the readme to clarify what the Coremark library is and how these projects are built.

2023-02-23 00:27 UTC, Jake-Carter commented on Examples/MAX32520/Coremark/README.md
> +This example determines the Coremark rating for the MAX32xxx and MAX78xxx series microcontrollers.
Needs more info on what Coremark is and what the example tells you.

2023-02-23 00:27 UTC, Jake-Carter commented on Examples/MAX32520/Coremark/project.mk
> +IPATH+=$(MAXIM_PATH)/Libraries/Coremark
Needs comments documenting the build setup

2023-02-23 00:27 UTC, Jake-Carter commented on Examples/MAX32520/Coremark/README.md
> +
Please add the following contents to the README, which have now become a part of the new [standard readme template in MSDKGen](https://github.com/Analog-Devices-MSDK/MSDKGen/tree/main/Markdown/Template).

```Markdown
### Project Usage

Universal instructions on building, flashing, and debugging this project can be found in the **[MSDK User Guide](https://analog-devices-msdk.github.io/msdk/USERGUIDE/)**.

### Project-Specific Build Notes

(None - this project builds as a standard example)
```

This project doesn't offer any build config options, but you may want to expand a bit on exactly where the source code is pulled from in the build notes section.

2023-02-23 00:28 UTC, Jake-Carter commented
@sihyung-maxim SVD verification is failing for this PR?

2023-02-24 15:51 UTC, Jacob-Scheiffler commented
> Yeah please add some comments to project.mk and some documentation in the readme to clarify what the Coremark library is and how these projects are built.

@Jake-Carter pretty sure I made all the changes you asked for, mind giving it another look?

2023-02-24 17:28 UTC, Jake-Carter approved these changes
Looks good!

2023-02-24 19:08 UTC, merged