prioritize HCI UART to avoid RX overrun
Analog-Devices-MSDK/msdk pull request #419
Opened 2023-02-14 16:09 UTC by EdwinFairchild

This seems to have stopped RX overrun issues. 
Still have SUP disconnects every once in a blue, but device does not need to be manually reset.
Rerunning the failed test can mitigate the issue, until true cause of SUP TIMEOUT is found.

2023-02-16 15:26 UTC, kevin-gillespie requested changes

2023-02-16 15:26 UTC, kevin-gillespie commented on Examples/MAX32655/BLE5_ctr/main.c
> +    NVIC_SetPriority(UART0_IRQn, 3);
Can we determine the IRQ from the HCI_UART/TERMINAL_UART definition?

2023-02-24 17:31 UTC, kevin-gillespie commented
Please apply these same changes to the other targets.

2023-02-24 18:53 UTC, EricB-ADI approved these changes

2023-02-24 19:57 UTC, EdwinFairchild commented
/clang-format-run

2023-02-25 06:48 UTC, merged