Tool to merge to hex files into one large hex file
Analog-Devices-MSDK/msdk pull request #467
Opened 2023-03-03 22:06 UTC by EricB-ADI

2023-03-03 23:13 UTC, yc-adi approved these changes

2023-03-06 13:36 UTC, kevin-gillespie requested changes

2023-03-06 13:36 UTC, kevin-gillespie commented on Tools/misc/hexmerge.py
> +## dtm_sweep.py
Update or remove these comments.

2023-03-06 13:36 UTC, kevin-gillespie commented
What's the purpose of this tool?

2023-03-06 14:56 UTC, EricB-ADI commented
We used it to merge the hex of the bootloader and the otas

2023-03-06 20:03 UTC, kevin-gillespie commented
We were able to include the .bin file with the gcc tools, so I don't think we need this.

2023-03-06 21:38 UTC, closed without merging