Integrate bootloader with OTAS program code
Analog-Devices-MSDK/msdk pull request #472
Opened 2023-03-06 19:53 UTC by AbbyWolf-ADI

Update OTAS makefiles to automatically compile and flash the bootloader application

2023-03-07 18:26 UTC, kevin-gillespie requested changes
I think we can add something like this to the client project.mk to build the .bin file without the bootloader section.

```bash
# Create binary output file without the bootloader
%.bin.noboot: %.elf
	@if [ 'x${VERBOSE}' = x ];                                                   \
	 then                                                                        \
	     echo "Creating ${@}";                                                   \
	     echo "Excluding bootloader section";                                    \
	 else                                                                        \
	     echo ${OBJCOPY} -O binary --remove-section .bootloader $(call fixpath,${<}) $(call fixpath,${@});    \
	 fi
	@$(OBJCOPY) -O binary --remove-section .bootloader $< $(call fixpath,${@})
```

2023-03-07 19:13 UTC, AbbyWolf-ADI commented on Examples/MAX32655/BLE_otas/project.mk
> +PROJ_CFLAGS += -Wl,--section-start=.text=0x10004000
doesn't look like we do, I've removed it

2023-03-09 20:31 UTC, kevin-gillespie requested changes
I think we accidentally added some documentation pictures and deleted one of the peripheral drivers.

2023-03-09 20:31 UTC, kevin-gillespie commented on Examples/MAX32655/BLE_otas/ota_internal_mem.ld
> +    }
We need the > BOOT here.

2023-03-10 20:14 UTC, EdwinFairchild approved these changes

2023-03-10 20:15 UTC, EdwinFairchild commented
Added a bug fix that this helped discover.

2023-03-10 20:20 UTC, kevin-gillespie approved these changes

2023-03-10 20:21 UTC, merged