fix me18 WLP_V1 PER failure
Analog-Devices-MSDK/msdk pull request #478
Opened 2023-03-09 17:35 UTC by yc-adi

@jhsiao2 Please test this PR on your setup for the ME18 WLP board. Thanks!

2023-03-09 17:41 UTC, kevin-gillespie requested changes
Please apply this change to all the targets.

2023-03-09 17:41 UTC, kevin-gillespie commented on Libraries/Cordio/platform/targets/maxim/max32690/sources/pal_cfg.c
> +  pCfg->dtmRxSyncMs           = 1; /* fix WLP_V1 PER failure */
We need to make the change in the above case as well.

2023-03-09 18:52 UTC, kevin-gillespie approved these changes

2023-03-13 18:31 UTC, jhsiao2 commented
received

2023-03-13 18:32 UTC, jhsiao2 approved these changes

2023-03-13 18:33 UTC, merged