RTC: Deprecating MXC_RTC_GetSubSecond and MXC_RTC_GetSecond
Analog-Devices-MSDK/msdk pull request #580
Opened 2023-05-08 18:48 UTC by Jacob-Scheiffler

This PR resolves JIRA ticket MSDK-1106 by deprecating the RTC functions GetSubSecond and GetSecond, and replacing them with GetSubSeconds and GetSeconds.

GetSubSecond/GetSecond were implemented incorrectly because the return value was used both to indicate whether an error had occurred and to return the count values of either the SEC or SSEC register. This was especially problematic for the SEC register since it is a 32-bit unsigned integer. Returning an error from GetSecond would aliases to a large SEC count, thus it was impossible to determine whether an error had occurred or the count value was simply a large value. (Note: this was not a bug for GetSubSecond since it is only a 12-bit unsigned value, but for consistency it has been deprecated too.)

The new functions solve this issue by taking a pointer to a uint32_t variable as a parameter and storing the current count of either the SSEC or SEC register to that address and the return value is now only used to indicate success/failure.

2023-05-09 17:53 UTC, Jake-Carter requested changes

2023-05-09 17:53 UTC, Jake-Carter commented on Libraries/PeriphDrivers/Include/MAX32670/rtc.h
> +int MXC_RTC_GetSecond(void) __attribute__((deprecated("Use MXC_RTC_GetSeconds() instead.")));
Looks good, we just need to wrap the attributes in a check for GCC so we don't break IAR/Keil

```C
/**
 * @brief     Get Second
 * @retval    returns second value or E_BUSY, see /ref MXC_ERROR_CODES
 */
#ifdef __GNUC__
__attribute__((deprecated("Use MXC_RTC_GetSeconds() instead.")))
#endif
int MXC_RTC_GetSecond(void);
```

2023-05-09 21:39 UTC, Jake-Carter approved these changes

2023-05-09 21:39 UTC, Jake-Carter approved these changes

2023-05-10 14:23 UTC, sihyung-maxim approved these changes

2023-05-10 14:23 UTC, merged