docs(Examples): Fix pin number for timer configuration
Analog-Devices-MSDK/msdk pull request #624
Opened 2023-06-14 21:04 UTC by Vignesh-VVadivel

Jira ticket for this issue is [here](https://jira.maxim-ic.com/projects/MSDK/issues/MSDK-1187?filter=allopenissues)

2023-06-14 23:23 UTC, Jake-Carter approved these changes

2023-06-15 14:26 UTC, Jacob-Scheiffler requested changes
P2.4 is connected to analog channel 4, however P2.4 is labeled "AIN1" on the Featherboard's silkscreen. For that reason, I think the README should remain unchanged, but I am open to discussion if you found the README misleading.

2023-06-16 00:13 UTC, Jake-Carter approved these changes

2023-06-16 11:54 UTC, Jacob-Scheiffler approved these changes

2023-06-16 18:51 UTC, merged