fix(Examples): MSDK-1194 Fix to select single SPI operating modes for the MAX78000
Analog-Devices-MSDK/msdk pull request #625
Opened 2023-06-14 22:04 UTC by Suraj-Ajjampur

As highlighted in [MSDK-1194](https://jira.maxim-ic.com/browse/MSDK-1194), there are 3 operating modes in the SPI example of the MAX78000. This fix ensures that a single operating mode is supported by the compiler by making changes to some pre-processor directives and the underlying logic.

2023-06-14 23:25 UTC, Jake-Carter approved these changes

2023-06-15 15:24 UTC, Jake-Carter commented
> See comment in [PR #622](https://github.com/Analog-Devices-MSDK/msdk/pull/622) about the README changes. The SPI example changes look good though!

Uno reverse card https://github.com/Analog-Devices-MSDK/msdk/pull/622#issuecomment-1593280837

2023-06-15 21:01 UTC, Jacob-Scheiffler requested changes

2023-06-15 21:01 UTC, Jacob-Scheiffler commented on Examples/MAX32650/SPI/README.md
> +The example can be configured to perform blocking (synchronous), non-blocking (asynchronus), or DMA transactions by setting the MASTERSYNC, MASTERASYNC, or MASTERDMA macro respectively.
Consider updating to match other READMEs.

2023-06-16 17:49 UTC, Jacob-Scheiffler commented on Examples/MAX32662/SPI/README.md
> +This example can demonstrate blocking, non-blocking, and DMA transactions methods controlled by the definitiona at the top of main. For blocking transactions define MASTERSYNC, for non-blocking trans
@Suraj-Ajjampur I agree that it's not critical for this release, but these inconsistencies tend to stick around for a long time so it's best to make it consistent while you're thinking of it.

2023-06-16 21:00 UTC, Suraj-Ajjampur commented
@Jacob-Scheiffler Changes made. Could you please approve and merge this?

2023-06-16 21:13 UTC, Jacob-Scheiffler approved these changes

2023-06-16 21:13 UTC, merged