feat(Examples): Update MAX32650 CLCD example to swap Maxim logo for ADI logo
Analog-Devices-MSDK/msdk pull request #658
Opened 2023-07-11 14:58 UTC by ronyaugustine

Original Example displays the Maxim logo. The ADI logo and tagline for the updated example are from the ADI logo kit found on the ADI intranet Circuit. C Bitmap array was generated using GIMP.

2023-07-11 15:42 UTC, sihyung-maxim approved these changes

2023-07-11 19:17 UTC, Jacob-Scheiffler approved these changes

2023-07-12 00:26 UTC, Jake-Carter requested changes
Looks good.  I would just request that you add some instructions for generating new bitmaps to the readme

2023-07-13 13:09 UTC, ronyaugustine commented
> Looks good. I would just request that you add some instructions for generating new bitmaps to the readme

Updated README with bitmap array generation instructions in the newest commit

2023-07-13 17:55 UTC, Jake-Carter approved these changes
Thanks!

2023-07-13 17:55 UTC, merged