feat(BLE, Examples): Add coded PHY long range demo on MAX32665
Analog-Devices-MSDK/msdk pull request #740
Opened 2023-09-21 15:51 UTC by yc-adi

Added Examples/MAX32665/BLE_LR_Peripheral and BLE_LR_Central to demonstrate coded PHY (S=8) for BLE long range mode.

2023-09-21 17:36 UTC, EricB-ADI commented
/clang-formtat-run

2023-09-21 17:47 UTC, EricB-ADI requested changes

2023-09-21 17:47 UTC, EricB-ADI commented on Examples/MAX32665/BLE_LR_Peripheral/fit_main.c
This file is still called fit_main.c should be ble_lr_periph_main.c or something

2023-09-21 17:47 UTC, EricB-ADI commented on Libraries/Cordio/ble-host/sources/hci/exactle/hci_core_ps.c
Can you not include "sch_int.h" without using a relative path? It should already be in the include path of the makefile.


You should use LL_TRACE instead of the printf.

2023-09-21 17:47 UTC, EricB-ADI commented on Libraries/Cordio/wsf/sources/targets/baremetal/wsf_os.c
wsf_os seems to be causing some build errors

2023-09-21 17:47 UTC, EricB-ADI commented on Libraries/Cordio/wsf/sources/targets/baremetal/wsf_msg.c
Can we delete this commented code?

2023-09-21 21:13 UTC, yc-adi commented on Libraries/Cordio/wsf/sources/targets/baremetal/wsf_os.c
Not sure what happened on your side.

2023-09-21 21:23 UTC, yc-adi commented on Libraries/Cordio/wsf/sources/targets/baremetal/wsf_os.c
Got the error.

2023-09-22 13:47 UTC, EricB-ADI commented
/clang-format-run

2023-09-22 15:59 UTC, EricB-ADI approved these changes

2023-09-22 18:52 UTC, victor-levi-maxim commented on Examples/MAX32665/BLE_LR_Central/main.c
> +#define DEFAULT_TX_POWER 0 /* dBm */
Default slave TX power is 4dBm, should default master TX power be 4 dBm as well for larger connection range?

2023-09-22 19:01 UTC, yc-adi commented
For the current customer application, the master only scans the for the EXT ADV. But for the general long range applications, 4 dBm TX power definitely will be helpful. I will change it from 0 dBm to 4 dBm.

Thanks!

From: Victor Levi ***@***.***>
Sent: Friday, September 22, 2023 1:53 PM
To: Analog-Devices-MSDK/msdk ***@***.***>
Cc: Cai, Ying ***@***.***>; Author ***@***.***>
Subject: Re: [Analog-Devices-MSDK/msdk] feat(BLE, Examples): Add coded PHY long range demo on MAX32665 (PR #740)

[External]


@victor-levi-maxim commented on this pull request.

________________________________

In Examples/MAX32665/BLE_LR_Central/main.c<https://urldefense.com/v3/__https:/github.com/Analog-Devices-MSDK/msdk/pull/740*discussion_r1334722826__;Iw!!A3Ni8CS0y2Y!9UDSYeD_WqTKEJQNWTczwtGqaiAIIPsJVc8QdIm3LSuWEv-0UW4nbnDl5W1nEFNPXo8t7YyD1das3i07Qf27cX-j$>:

> +

+#include "pal_bb.h"

+#include "pal_cfg.h"

+#include "pal_timer.h"

+#include "pal_sys.h"

+

+#include "lr_central_api.h"

+#include "app_ui.h"

+

+/**************************************************************************************************

+  Macros

+**************************************************************************************************/

+

+/*! \brief UART TX buffer size */

+#define PLATFORM_UART_TERMINAL_BUFFER_SIZE 2048U

+#define DEFAULT_TX_POWER 0 /* dBm */

Default slave TX power is 4dBm, should default master TX power be 4 dBm as well for larger connection range?

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/Analog-Devices-MSDK/msdk/pull/740*pullrequestreview-1640490987__;Iw!!A3Ni8CS0y2Y!9UDSYeD_WqTKEJQNWTczwtGqaiAIIPsJVc8QdIm3LSuWEv-0UW4nbnDl5W1nEFNPXo8t7YyD1das3i07QXI0R7CI$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/A2NWXE2UPZOCQZSDFIIH72DX3XNA7ANCNFSM6AAAAAA5BYXBGY__;!!A3Ni8CS0y2Y!9UDSYeD_WqTKEJQNWTczwtGqaiAIIPsJVc8QdIm3LSuWEv-0UW4nbnDl5W1nEFNPXo8t7YyD1das3i07QfsU_4jw$>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2023-09-23 00:28 UTC, victor-levi-maxim approved these changes

2023-09-25 13:35 UTC, EricB-ADI commented
One last thing. Is there a reason the adverting name is LongRang and not LongRange?

2023-09-25 15:23 UTC, merged