fix(PeriphDrivers): Update ME12's GPIO PAD configuration
Analog-Devices-MSDK/msdk pull request #874
Opened 2024-01-15 11:29 UTC by hfakkiz

## Pull Request Template

### Description

ME12 only supports high-impedance, weak pullup and weak pulldown options.

![image](https://github.com/Analog-Devices-MSDK/msdk/assets/94184469/64b08d1f-7688-4bc2-ab46-b7f6f1856a99)

This commit removes other options and corrects related register values of PAD configuration.

### Checklist Before Requesting Review

- [ ] PR Title follows correct guidelines.
- [ ] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

2024-01-15 16:40 UTC, sihyung-maxim commented
This PR is related to this one: https://github.com/Analog-Devices-MSDK/msdk/pull/866

The final changes should be consistent across these two PRs.

2024-01-15 20:11 UTC, Jake-Carter requested changes
To maintain consistency, I think we should also apply the approach in #866.

In this case, since _weak_ pull-ups are only supported, the enum can be defined as:

```C
/**
 * @brief   Enumeration type for the type of GPIO pad on a given pin.
 */
typedef enum {
    MXC_GPIO_PAD_NONE, ///< No pull-up or pull-down
    MXC_GPIO_PAD_WEAK_PULL_UP, ///< Set pad to weak pull-up
    MXC_GPIO_PAD_WEAK_PULL_DOWN, ///< Set pad to weak pull-down
    MXC_GPIO_PAD_PULL_UP = MXC_GPIO_PAD_WEAK_PULL_UP, ///< Not supported by hardware.  This sets a weak pull-up instead.
    MXC_GPIO_PAD_PULL_DOWN = MXC_GPIO_PAD_WEAK_PULL_DOWN, ///< Not supported by hardware.  This sets a weak pull-down instead.
} mxc_gpio_pad_t;
```

2024-01-17 10:52 UTC, ozersa commented
@sihyung-maxim correct the changes shall be consistent.

Default pullup pulldown shall be "MXC_GPIO_PAD_PULL_UP" and "MXC_GPIO_PAD_PULL_DOWN" to be consistent and simplify things. The below configuration will work on Zephyr side.

gpio.h file
```
typedef enum {
    MXC_GPIO_PAD_NONE, ///< No pull-up or pull-down
    MXC_GPIO_PAD_PULL_UP, ///< Set pad to weak pull-up
    MXC_GPIO_PAD_PULL_DOWN, ///< Set pad to weak pull-down
    MXC_GPIO_PAD_WEAK_PULL_UP = MXC_GPIO_PAD_PULL_UP, ///< Set pad to weak pull-up
    MXC_GPIO_PAD_WEAK_PULL_DOWN = MXC_GPIO_PAD_PULL_DOWN, ///< Set pad to weak pull-down
} mxc_gpio_pad_t;
```

gpio_me12.c file
```
    switch (cfg->pad) {
    case MXC_GPIO_PAD_NONE:
        gpio->padctrl0 &= ~cfg->mask;
        break;

    case MXC_GPIO_PAD_PULL_UP:
        gpio->padctrl0 |= cfg->mask;
        gpio->ps |= cfg->mask;
        break;

    case MXC_GPIO_PAD_PULL_DOWN:
        gpio->padctrl0 |= cfg->mask;
        gpio->ps &= ~cfg->mask;
        break;

    default:
        return E_BAD_PARAM;
    }
```

2024-01-17 12:47 UTC, hfakkiz commented
> @sihyung-maxim correct the changes shall be consistent.
> 
> Default pullup pulldown shall be "MXC_GPIO_PAD_PULL_UP" and "MXC_GPIO_PAD_PULL_DOWN" to be consistent and simplify things. The below configuration will work on Zephyr side.
> 
> gpio.h file
> 
> ```
> typedef enum {
>     MXC_GPIO_PAD_NONE, ///< No pull-up or pull-down
>     MXC_GPIO_PAD_PULL_UP, ///< Set pad to weak pull-up
>     MXC_GPIO_PAD_PULL_DOWN, ///< Set pad to weak pull-down
>     MXC_GPIO_PAD_WEAK_PULL_UP = MXC_GPIO_PAD_PULL_UP, ///< Set pad to weak pull-up
>     MXC_GPIO_PAD_WEAK_PULL_DOWN = MXC_GPIO_PAD_PULL_DOWN, ///< Set pad to weak pull-down
> } mxc_gpio_pad_t;
> ```
> 
> gpio_me12.c file
> 
> ```
>     switch (cfg->pad) {
>     case MXC_GPIO_PAD_NONE:
>         gpio->padctrl0 &= ~cfg->mask;
>         break;
> 
>     case MXC_GPIO_PAD_PULL_UP:
>         gpio->padctrl0 |= cfg->mask;
>         gpio->ps |= cfg->mask;
>         break;
> 
>     case MXC_GPIO_PAD_PULL_DOWN:
>         gpio->padctrl0 |= cfg->mask;
>         gpio->ps &= ~cfg->mask;
>         break;
> 
>     default:
>         return E_BAD_PARAM;
>     }
> ```

Updated code as this.

2024-01-19 19:45 UTC, Jake-Carter approved these changes
In my mind it makes more sense to define the weak pull-ups as the main ones, but if this helps simplify the Zephyr port then this works too

2024-01-19 19:45 UTC, merged